# Generated by Django 3.1.4 on 2020-12-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='day',
            field=models.IntegerField(),
        ),
    ]
